server:
  port: 8080
  shutdown: graceful
  tomcat:
    graceful-shutdown-wait: 30s
    additional-tld-skip-patterns: "*.jar"
  error:
    whitelabel:
      enabled: false
  thymeleaf:
    cache: false

spring:
  mvc:
    throw-exception-if-no-handler-found: true